webtalk_init -webtalk_dir C:/FPGA_Projects/MD5-in-Verilog/MD5-in-Verilog.sim/sim_1/behav/xsim/xsim.dir/MD5_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Sep 28 09:17:16 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4177d818-4d7a-4f5b-af9d-3f0e5482b477" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c0cb9ba40602438ca14654924f5bdbb4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "88" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "4" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "1163 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "62 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "601" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "67" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "7.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "156680_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3839121345 -regid "" -xml C:/FPGA_Projects/MD5-in-Verilog/MD5-in-Verilog.sim/sim_1/behav/xsim/xsim.dir/MD5_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/FPGA_Projects/MD5-in-Verilog/MD5-in-Verilog.sim/sim_1/behav/xsim/xsim.dir/MD5_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/FPGA_Projects/MD5-in-Verilog/MD5-in-Verilog.sim/sim_1/behav/xsim/xsim.dir/MD5_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
